-- This file will become init.lua and replace init.vim when home-manager starts to support this approach
require('basic')
require('completion')
require('haskell')
require('json')
require('keys')
require('lua-config')
require('misc')
require('nix')
require('notify-config')
require('scala')
require('statusline')
require('telescope-config')
require('theme')
require('tree')
